### PR TITLE
#1050 update dependencies part two

### LINKED ISSUE #1050: Upgrading dependencies part two
## Describe
- AsyncStorage within `react` is deprecated, want to replace it with @react-community/async-storage. This will enable upgrading `redux-persist` with no issues once 6.0 is released.
- Want to upgrade realm. 
- Want to remove the following devDependencies (and just start fresh with a new testing framework)
    - `sinon`
    - `react-native-mock`
    - `enzyme`
    - `expect`
    - `expect-jsx`
    - `react-addons-test-utils`
    - `promise-sync-es6`
    - `flow-bin`
- upgrade any remaining devDependencies
### To reproduce
N/A

### Expected behaviour
N/A

### Version and device info
 - App version: 2.3.4
 - Tablet model: All
 - OS version: All

### Additional context
Have already upgraded many dependencies in the develop branch, this will finish off upgrading/removing.

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1050 

## Change summary
- Realm 2.22 -> 2.29
    - https://github.com/realm/realm-js/blob/master/CHANGELOG.md
    - Realm.create changes - have tested and doesn't seem to effect us. Should be careful with this though, I might need to revert this and make changes in another PR to accomadate
    - support for higher versions of react
    - `The parser now supports readable timestamps with a T separator in addition to the originally supported @ separator. For example: startDate > 1981-11-01T23:59:59:1.`
    - `It is now possible to store Realms on Android external storage with React Native by using Realm.Configuration.fifoFilesFallbackPath`
    - `When creating objects using migration, a native crash could occur if a new optional property was added to the schema. (#1612, since v1.0.0)` - I remember seeing an issue related to migration but can't find it, could help
- Added: @react-community/async-storage
    - `React.AsyncStorage` is deprecated
- removed a few dependencies which weren't in use as per the linked issue 
- Added 64bit APK - **this has increased the size of the APK from 15.8Mb to 33.4Mb**
- Added upgrades for all the formatters and linters

## Testing
Steps to reproduce or otherwise test the changes of this PR:
- [ ] Can build and run the app
- [ ] Runs as per normal
- [ ] Specifically, testing realm creating of records
- [ ] Runs on both 32 bit and 64 bit architectures (using either x86 or ARM)

### Related areas to think about
Should be about it for upgrades for dependencies. Bring on dependabot? :) 

Also the realm.js query language is pretty light on documentation from what I can tell, however it does have a whole bunch of new toys that we could/should be using!

### CODE REVIEW

**Comment by joshxg** [comment]
Have added a new commit to update `react-devtools-core` to remove a warning during building and also for `lodash` due to the security warning regarding prototype pollution. These are both sub-dependencies which have had their versions set in `resolution` field in `package.json` (`react-devtools-core` was already there and `lodash` is a depended on by packages which have not released a minor version yet that use the latest `lodash`, fixing the prototype-polution problem

**Comment by joshxg** [comment]
I would be keen to have one more review, if possible due to this having quite a lot of unintended consequences (main one being the app breaking), before being merged. I'm also wondering if this should be tested on specific devices i.e. the tablet IC uses, possibly others (maybe emulating these devices) due to the build script changing

**Comment by Chris-Petty** [comment]
@sworup @raviSussol would one of you be able to review/test this week please? Speaking of, does the KTM office have one of the techno tablets that IC has?

**Comment by raviSussol** [comment]
@Chris-Petty Sure will test it this week. No we don't have any Tecno tablet with us (i.e. only have Samsung and Lenovo).

**Comment by raviSussol** [comment]
On the second thought, we (KTM office) decided to buy one Tecno tablet. Perhaps, we may get it from [#TecnoNepal](https://www.facebook.com/TECNOMobileNepal/)

**Comment by joshxg** [comment]
Hi @raviSussol did you guys end up getting a techno tablet?

**Pull request merged**
