### PR TITLE
#3308 New Editing rows

### LINKED ISSUE #3308: New editing rows
*EPIC: #3161*

*Related Marvel Designs: https://marvelapp.com/prototype/55aea8f*
*Related Component Breakdown: https://app.diagrams.net/#G1wLg12JAQyrgB6D3F_X0O9LBZwJs8PcJM

## Is your feature request related to a problem? Please describe.

In the new vaccine module designs there are different style of editing rows:

Examples:

image
image
image

This issue is to discuss the implementation of these editable areas to try and create a solution which easily enables different styles of rows to edit different fields.

## Describe the solution you'd like

Unsure 100% just yet.

Still thinking about the API for this. I think I would like to see some sort of `Row` style component which can be composed of different `RowEdit` components?

Something like:

```
<Row>
    <RowLabel icon="X" text="Y"/>
    <RowTemperatureEdit currentValue={} someCallbacks/>
    <RowDurationEdit currentValue={} someCallbacks/>
</Row>
```

## Implementation

Create components:

- [ ] `TextInputWithMask`
- [ ] `TextInputWithAffix`
- [ ] `BaseStepperButton`
- [ ] `BaseStepperInput`
- [ ] `StepperInputWithLabel`
- [ ] `DurationEditor`
- [ ] `TemperatureEditor`
- [ ] `TimeEditor`
- [ ] `DateEditor`
- [ ] `TextEditor`
- [ ] `EditorRow`

## Describe alternatives you've considered

TBD

## Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3308

## Change summary

- Bunch of components for to create a form as below

## Testing

Internal

### Related areas to think about

image

### CODE REVIEW

**Comment by joshxg** [comment]
image

**Review by katherine-sussol — APPROVED** [review]
Coool, had a fiddle around with it, seems good to me 👍

**Comment by joshxg** [comment]
@katherine-sussol @Chris-Petty 

I've merged all the PR's into this single branch

**Review by katherine-sussol — APPROVED** [review]
This all looks like it's working well and looks good visually. 

I think I just have questions rather than suggestions as I'm still figuring out what things are and aren't ideal w.r.t components and structure.
- Where would `BaseStepperInput` fit in with the old `Stepper/StepperInput/StepperRow` components (e.g. if another place needed a stepper, would we try to use `BaseStepperInput` going forward? It kind of looks a little more generic? Would this be something to (later) rejig to use the ones in this PR?)
- I'm unsure about the component `WithFixedDimensions`, is this mainly a way to avoid an inline style?

**Comment by joshxg** [comment]
> Where would BaseStepperInput fit in with the old Stepper/StepperInput/StepperRow components (e.g. if another place needed a stepper, would we try to use BaseStepperInput going forward? It kind of looks a little more generic? Would this be something to (later) rejig to use the ones in this PR?)

This is a good question. Yeah the `StepperInput` component was made too specific to the use case and I didn't want to spend the time rejigging (primarily because I think the professionally designed vaccine stuff will hopefully replace a lot of the dispensing stuff where the old stepper was used which had no professional designer - but this is more of a hope from me rather than anything that is properly planned).

As much as I think I create too many components and potentially prematurely abstract, if I had created a "BaseStepper" originally and split that original component up more, then there would have been some base to work from for this. 

> I'm unsure about the component WithFixedDimensions, is this mainly a way to avoid an inline style?

Yes. I dont really like inline styles and writing a bunch of css in components ..

**Pull request merged**
