### PR TITLE
#4949 allow setting editable from login page

### LINKED ISSUE #4949: Ability to change Sync URL  and site password from the mobile login window
## Is your feature request related to a problem? Please describe.

While supporting Mobile, it was evident that `Site setting` needs to be modifiable from the mSupply Mobile Login window. 

The problem : 

* A client has a Mobile issue.
* With great difficulty we get the Mobile data file. 
* We import to the local mobile tablet.
* **Problem :** It attempts to sync to the live server. We have no easy way to re-point to another clone system. 

## Describe the solution you'd like

- We have the mSupply login window as shown. 
- Lets have a setting icon. When clicked we will display a `Authorisation` window with Hardcoded password that we know.
-Once password is correctly entered, we need the following window to show the following details : 
- Site name :  [data not changeable]
- Site ID : [data not changeable]
- Site password : [Password to be update-able]
- Site URL : [URL to  update-able]
- We need a [save] and [back]
- If we have the above feature then testing and debugging mobile issue will be easier. 

Mobile_site_and_url_chnage

## Implementation

n/a

## Describe alternatives you've considered

n/a

## Additional context

I think there is a setting page that you can get to once you login. So perhaps a review and we just expose this page at the beginning.

### PR DESCRIPTION
**Pull request by arjunSussol**
Fixes #4949 

## Change summary

Added `Sync site ID` and `Sync site name` to `SettingPage` , both fields are non editable.
Allow to visit `SettingPage` from `LoginPage` with label `SETTINGS`.
Added environment variable (.env) which is ignored in git, but there is .env.example file with same key without value.
.env file should have admin password which is not store in mobile database.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] First, sync database then go to Login page.
- [ ] At `Login` page there is `SETTINGS` label in bottom.
- [ ] Click Settings alert with input field which required valid password
- [ ] Entered admin password and click `Done` button
- [ ] If password is valid then Setting page should be visible
- [ ] In Setting page, change the editable fields then click `Save` button
- [ ] Alert with input field which required valid password.
- [ ] Enter valid admin password as same as above entered password.
- [ ] If valid password entered then it will save settings and related pop up visible, otherwise not.

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

### CODE REVIEW

**Review by sworup — CHANGES_REQUESTED** [review]
@arjunSussol I tried to run your code locally on my computer and the login part works fine.

However, have you tried to click the Save changes and Realm Explorer buttons. During my test, saven changes asks for the password and when I give it REACT_APP_ADMIN_PASSWORD_HASHED password, it fails to login. The language actually says I need to give user password, but after your changes user password would not have been entered yet so if it uses user password we would need to change that to this admin password or sync password.

Yes, we store user password and after first login it might work but that defeats the purpose of moving this setting UI outside and putting it in login page.

Same for factory reset and other buttons.

Another thing I noticed is we would still need this setting section inside after user had logged in. So if you change this password to admin password or sync password, maybe we have to set it back to user password when the UI opens inside because users would not know sync or admin password.

Another interesting thing, we added a package and used the env variable but it just dawned on me that since we had already used sync password to get to this point and sync password is saved in our mobile database. Maybe we should use that. People who know the sync password are admins anyway so they should be able to see the data. If we are using User password inside, sync password is actually more secure. 

So I think we can use sync password for this admin interface and avoid using env file. 

https://github.com/openmsupply/mobile/blob/9ecf8683e74d9cad797191f44c500ca3cd6f5fe6/src/pages/SettingsPage.js#L122-L125

Can you please experiment and try and see if you can use sync password instead of admin password.

**Comment by arjunSussol** [comment]
@sworup @ujwalSussol 
After discussion I have fix issues raised by @sworup above.
Please, review this again.

**Review by ujwalSussol — APPROVED** [review]
@arjunSussol  : thanks for the code overview. The user interface looks great.
@sworup and @arjunSussol : Thanks for helping to get this running... 👍  I am learning new things 👍

**Comment by ujwalSussol** [comment]
@AnushaUp and @santoshkhanal12   :   could you test this APK.

https://drive.google.com/drive/u/0/folders/1EhyC6ANWxV_UqiPpIV0rHAV2EjzEwpbR

**Comment by AnushaUp** [comment]
Tested With latest APK: `https://github.com/openmsupply/mobile/tree/%234949-Allow-setting-editable-from-login-page`

@arjunSussol 
In this screen below which is the the just after login there is no setting button.
photo_2022-11-11 17 55 56

In this login window the screen is not responsive and setting section is showing up in the wrong section.
photo_2022-11-11 17 56 00

**Review by sworup — APPROVED** [review]
Looks good and tested well.

**Comment by arjunSussol** [comment]
@AnushaUp @sworup the setting visibility on Login window should be fixed by this PR: https://github.com/openmsupply/mobile/pull/5001

The another issue can be recreated. I still notice the Settings functionality inside Navigator window.

**Pull request merged**
