### PR TITLE
#4182 only count active sensors in breach

### LINKED ISSUE #4182: Breach notification badge should only display a badge when active sensors are in breach
## Describe the bug

Currently, the 'sensors in breach' badge count is incremented even if a sensor has been inactivated (but was inactivated while still in breach).

### To reproduce

Steps to reproduce the behaviour:

1. Set up a sensor and have it enter a breach
2. Select 'Remove Sensor'
3. Cold Chain Badge count should go down (but it doesn't)

### Expected behaviour

Cold Chain Badge count should only increment if an _active_ sensor is in breach

### Proposed Solution

Add check for isActive flag on sensors when populating badge counts

### Version and device info

- App version: 8.1.0
- Tablet model:
- OS version:

### Additional context

N/A

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #4182 

## Change summary

Added sensor.isActive check when calculating cold chain badge count
Targetting master just because I think we would like it patched before the demo tomorrow.
Now I am unsure about `isPaused` as well but I think it's a little more obvious from the UI at least if a sensor is paused.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Reproduce #4182

### Related areas to think about

N/A

### CODE REVIEW

**Review by joshxg — COMMENTED** [review]
Cool! but whats going on with these diffs 🤔

**Comment by katherine-sussol** [comment]
> Cool! but whats going on with these diffs 🤔

Good question haha I think maybe it's because I created my branch off develop but then targetted master...

**Comment by joshxg** [comment]
Hmm yeah some hunchy funchy gone on.. maybe be a good idea to create a `release/8.1.1` branch off develop to merge these PRs into? then that can be merged into master?

That way we can keep master clean and develop can still have PRs go in which aren't for the `8.1.1` patch

**Comment by katherine-sussol** [comment]
Closing this weiiiird PR

**Pull request closed without merging**
