### PR TITLE
#2460 add duplicate policy number validation

### LINKED ISSUE #2460: Prevent duplicate policy numbers
## Is your feature request related to a problem? Please describe.

All policies for a given provider should have distinct policy numbers. This is currently enforced on desktop but not on mobile.

## Describe the solution you'd like

When entering a new policy, the policy can only be saved if the policy number does not already exist for that provider.

## Implementation

Tidiest way of doing this at the moment is to share state between inputs by passing a `form` prop to `Form` components (e.g. `FormTextInput`). This can then be passed as an optional parameter to the validation function.

## Describe alternatives you've considered

N/A.

## Additional context

N/A.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2460.

Branches off #2459.

## Change summary

Took a bit of time to get there, but a minor refactor with a bit of a workaround to make policy number validation consistent with desktop behaviour.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] If a duplicate policy number is entered, both the personal and family form inputs provide a warning.
- [ ] If either personal or family form inputs are updated such that the policy number is no longer equal to an existing policy number, both personal and family form inputs warnings are no longer displayed.
- [ ] When testing the previous two tests, the personal AND family warnings are synchronised, i.e. either both display a warning, or neither.

### Related areas to think about

Not the tidiest fix, I think may need a bit of refactoring when more time is available.

### CODE REVIEW

**Comment by mark-prins** [comment]
Hm. I don't think that it fixes #2469 more likely #2458

**Comment by wlthomson** [comment]
Update: had to do some rebasing and cherry-picking to rewrite the history to be based on `master` not `develop`. No code changes.

**Comment by wlthomson** [comment]
@mark-prins Have addressed both your usage things. Will wait for you to give it another look before merging.

I agree re. the message, but if we want to patch we will have to also get it translated, so maybe best for a separate issue?

Key thing is that without doing some refactoring, there isn't a way to specify more than one error message per input, so I think the strategy might be to get this in so we are enforcing the constraints we need to for the patch, and getting the rest of it sorted out in the next release?

**Comment by Rebecca367** [comment]
Nicely done!

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [x] If a duplicate policy number is entered, both the personal and family form inputs provide a warning.
- [x] If either personal or family form  puts are updated such that the policy number is no longer equal to an existing policy number, both personal and family form inputs warnings are no longer displayed.
- [x] When testing the previous two tests, the personal AND family warnings are synchronised, i.e. either both display a warning, or neither.
Screen Shot 2020-03-24 at 3 34 22 PM

**Pull request merged**
