### PR TITLE
#2939 keyboard dissapearing

### LINKED ISSUE #2939: Entering batch/quantity value against supplier invoice > Tablet keyboard disappear
## Describe the bug

Entering the batch details / quantity to supply leads to disappear keyboard.

### To reproduce

1. Go to 'Supplier invoice'
2. Click on 'Batch or quantity' to put in > doesn't happen always need to play with it > or need to add a new line.
3. Single/double tap or put the cursor at the end > No disappear of keyboard
4. See Keyboard get disappear when selecting batch column / quantity

### Expected behaviour

consistent

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.0.1
- Tablet model: Samsung
- OS version: Android

### Additional context

See video:
https://www.dropbox.com/s/3dv1gnj5isb1lqo/supplierinvoice.mp4?dl=0
https://www.dropbox.com/s/m50fa43ujqgluli/video-1591800520.mp4?dl=0

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2939 (and a few others)

## Change summary

- Added a footer component which will animate to the height of the keyboard rather than a static value which I knew would never be sufficient. Oops.
- Added use of the `adjustToTop` function, which I'm pretty sure I made originally for this exact purpose but I didn't actually *use* it. Oops.

## Testing

- [ ] Clicking a row which would normally be hidden by the keyboard does not make the keyboard dismiss

### Related areas to think about

This can be improved further, by adjusting the amount rows are scrolled, and also only scrolling when really needed with some better logic. But, lets see if this works properly for now, right @bijaySussol  :)

Have uploaded an APK on JOTTA CLOUD > mSupply Mobile folder

### CODE REVIEW

**Review by wlthomson — APPROVED** [review]
lgtm

**Review by bijaySussol — CHANGES_REQUESTED** [review]
@joshxg : 

With testing against emulator- requesting changes - Still disappearing - please see GIF

http://g.recordit.co/HWHIu9POnV.gif [ Help to see on browser ]

**Comment by joshxg** [comment]
@bijaySussol Whaaaat

I have pushed a new commit. This is what mine looks like:


This APK for the latest commit is on JOTTA CLOUD > `test apk 1.zip`

## Large list - WITHOUT FIX

bad-big

## Small list - WITHOUT FIX

bad-small

## Small list - WITH FIX

good-small


## Long list - WITH FIX

good-big

**Comment by bijaySussol** [comment]
@joshxg : 

Still seeing keyboard disappearing:

http://g.recordit.co/jBMLuTj7DA.gif

I build a APK from this PR changes and tested on Emulator.

BTW: I am testing supplier invoice hopefully is the same fix across others

**Review by bijaySussol — APPROVED** [review]
@joshxg : 

I must have done some funny with the custom APK build against this PR but i did it correctly :-( 

With the apk you sent today - Tested against the same datafile against same invoice (Supplier) - It is behaving properly.

Nice work, would be keen to test this against the final build app
For now - This is good to go from my end (testing point of view) 

Approved!

**Comment by joshxg** [comment]
@bijaySussol  Just good we have a fix, finally!!!! Thanks ❤️

**Comment by Gwalior-84** [comment]
Does this mean we will have a new release soon @joshxg ?

**Comment by joshxg** [comment]
@Gwalior-84 Yup - https://github.com/openmsupply/mobile/issues/2722#issuecomment-732447425 (Will keep the release talk there even though it's been neglected, sorry)

**Pull request merged**
