### PR TITLE
#2115 Portuguese translations

### LINKED ISSUE #2115: Portugese language support
## Is your feature request related to a problem? Please describe.

We don't currently support portugese

## Describe the solution you'd like

To support portugese

## Implementation

This can probably be split over a few issues!

- Add a portugese language code, flag and add it to the modal selection for languages on the login page.
- Add the portugese code to all the `JSON` files
- export the localization files, add the translations and reimport!

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes #2115 

## Change summary

Just adding support to Portuguese language

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Check that "Português" can be selected in the languages menu
- Check that Portuguese strings are not being cut in:
  - [ ] Initial setup (to select which store to sync) window
  - [ ] Main window buttons
  - [ ] Sync window
  - [ ] Login window
  - [ ] Stocktakes list window
  - [ ] New Stocktake window
  - [ ] Customer Invoices list window
  - [ ] New Customer Invoice window
  - [ ] Customer Requisitions list window
  - [ ] New Customer Requisition window
  - [ ] Supplier Invoices list window
  - [ ] New Supplier Invoice window
  - [ ] Supplier Requisitions list window
  - [ ] New Supplier Requisition window
  - [ ] Dashboard(?)
  - [ ] Dispensary patients list window
  - [ ] Dispensary prescriptions list window
  - [ ] Dispensary New patients window
  - [ ] Dispensary New prescription window
  - [ ] Any other places?

### Related areas to think about

Not tested by developer. Sorry!

### CODE REVIEW

**Comment by joshxg** [comment]
@nmadruga will have a look straight after UAT! :) 

I think we just need a flag icon though!

**Comment by nmadruga** [comment]
Here it is @joshxg. Thanks for the reminder.

**Comment by nmadruga** [comment]
Thanks Josh! I'll be testing now and creating another similar branch - It seems easier than making a `git rebase` on this one. I'll test it quickly and then re-make the PR.

**Comment by nmadruga** [comment]
PR recreated here: https://github.com/openmsupply/mobile/pull/2337

**Pull request closed without merging**
