### PR TITLE
#786 Incoming sync sets cost price based on sell price on item batch

### LINKED ISSUE #786: Incoming sync sets cost price based on sell price on itemBatch
**Build Number:**  Been like this for 2 years. Just everything. Today it's 2.2.0-rc0 though.

# Description

https://github.com/openmsupply/mobile/blob/6058be29f51630154f74dc37f2c796e72c850673/src/sync/incomingSyncUtils.js#L105
This line above shows sell price being used for cost price. If this is somehow intentional it needs a comment explaining it, but sure just looks like a small mistake.

Reproducible: Doesn't really affect anything I can think of.

Reproduction Steps:

Comments:

### PR DESCRIPTION
**Pull request by sworup**
Fixes #786

- Since the original code seems to be a typo.

### CODE REVIEW

**Comment by Chris-Petty** [comment]
@UjwalSussol @GaryWilletts Just a wee check, I wasn't delusional and this is a typo yea?

**Comment by GaryWilletts** [comment]
It looks like a typo. Are both values being sent to mobile from 4D? There is a chance that the only value sent is the sell price, which would explain the original code (in which case a comment would have been good).

**Comment by sworup** [comment]
> It looks like a typo. Are both values being sent to mobile from 4D? There is a chance that the only value sent is the sell price, which would explain the original code (in which case a comment would have been good).

@GaryWilletts Yes both values are coming in from 4D. 

I traced the values coming in during sync and here's what I found-
- In many cases cost_price and sell_price were same values.
- Cost price and Sell price were coming in as different number values on numerous occasions (say 10% of all).
- There were cases where the response from the server is sending in cost_price as a value but sell_price as 0.
- In all instances where there is a sell_price coming in, there is definitely a cost price that accompanied it.

```
02-05 17:56:04.389  3641  3681 I ReactNativeJS: Cost Price => 0
02-05 17:56:04.390  3641  3681 I ReactNativeJS: Sell Price => 0
02-05 17:56:04.390  3641  3681 I ReactNativeJS: ======================================
02-05 17:56:04.090  3641  3681 I ReactNativeJS: Cost Price => 7.67
02-05 17:56:04.090  3641  3681 I ReactNativeJS: Sell Price => 0
02-05 17:56:04.090  3641  3681 I ReactNativeJS: ======================================
02-05 17:56:04.092  3641  3681 I ReactNativeJS: Cost Price => 125
02-05 17:56:04.092  3641  3681 I ReactNativeJS: Sell Price => 0
02-05 17:56:04.092  3641  3681 I ReactNativeJS: ======================================
02-05 17:56:04.095  3641  3681 I ReactNativeJS: Cost Price => 2.08
02-05 17:56:04.095  3641  3681 I ReactNativeJS: Sell Price => 2.08
02-05 17:56:04.095  3641  3681 I ReactNativeJS: ======================================
02-05 17:56:04.406  3641  3681 I ReactNativeJS: Cost Price => 0.01
02-05 17:56:04.406  3641  3681 I ReactNativeJS: Sell Price => 0.005
```

**Comment by GaryWilletts** [comment]
Thanks @sworup , I think it's safe to assume it's a typo so I'll approve it. Go me, reviewing React code...

**Pull request merged**
