### PR TITLE
#3281 New Dep: react-native-ble-plx

### LINKED ISSUE #3281: Add react-native-ble-plx
## Is your feature request related to a problem? Please describe.

[ble-plx package](https://github.com/Polidea/react-native-ble-plx) is nice!

## Describe the solution you'd like

Add https://github.com/Polidea/react-native-ble-plx dependency

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3281

## Change summary

- Adds `react-native-ble-plx`

## Testing

- [ ] ??

### Related areas to think about

N/A

### CODE REVIEW

**Comment by Chris-Petty** [comment]
Josh already knows but it BORK:

image

**Comment by joshxg** [comment]
Sorry!!! 03920bc

I forgot about minSdk - as for main application, the BlePacker is conflicting between the new module and our own native module.

**Comment by joshxg** [comment]
Have updated with @Chris-Petty 's develop fix

**Review by katherine-sussol — DISMISSED** [review]
Is working for me 👍  - I don't know what else to check, but good to know where dependencies live 👀

**Comment by joshxg** [comment]
❤️

**Pull request merged**
