### PR TITLE
#4406 Add prescription records to vaccination name_notes

### LINKED ISSUE #4406: Add prescription data to name_note records created on vaccination
## Is your feature request related to a problem? Please describe.

Would like vaccination details (e.g. doses, transaction id) available via name_note records. 
Vaccination history is now synced/retrieved in mobile via name_note records - some info is currently missing from these which could make life difficult if multi-dose dispensing ever becomes a thing (and also makes linking back to the original transaction difficult for reporting/filtering if needed).

## Describe the solution you'd like

name_note data payload to have prescription data:
```
{
  "refused": false,
  "batch": "batch_2",
  "bonusDose": false,
  "vaccinator": "MA Medicine Administrator",
  "itemName": "COVID19 Vaccine AstraZeneca",
  "expiry": "2024-11-29T11:00:00.000Z",
  "vaccineDate": "20/08/2021",
  "itemCode": "COV1",
  "refusalReason": "",
  "extra": {
    "vaccinator": {
      "code": "MA",
      "firstName": "Medicine",
      "lastName": "Administrator",
      "isActive": true
    },
    "prescription": {
      "id": "some_id",
      "entryDate": "someEntryDate",
    }
    ...
}
```

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

Leaving as is

## Additional context
Arisen from #4347 - currently doing duplicate detection between local/remote transactions based on date/item id (whereas ideally we would use the prescription id)

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #4406

## Change summary

- Adds prescription details into vaccination `name_note` records

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Create a vaccination, check in realm explorer (or sync and check mSupply desktop record browser), payload should include prescription details, e.g:
```
{
  "refused": false,
  "bonusDose": false,
  "itemName": "COVID19 Vaccine AstraZeneca",
  "itemCode": "COV1",
  "batch": "batch_1",
  "expiry": "2024-12-30T11:00:00.000Z",
  "vaccineDate": "14/09/2021",
  "vaccinator": "MA Medicine Administrator",
  "refusalReason": "",
  "extra": {
    "prescription": {
      "id": "843c3a90151c11ec98594f358ecd0458",
      "serialNumber": "92",
      "comment": "",
      "customData": "{\"country\":\"Kiribati\"}",
      "entryDate": 1631597276344,
      "type": "customer_invoice",
      "status": "finalised",
      "confirmDate": 1631597276344,
      "enteredBy": "0763E2E3053D4C478E1E6B6B03FEC207",
      "theirRef": null,
      "items": [
        {
          "id": "843cd6d0151c11ec98594f358ecd0458",
          "item": {
            "id": "F326CB5105694DAD8A07AE1957CD512B",
            "code": "COV1",
            "name": "COVID19 Vaccine AstraZeneca",
            "defaultPackSize": 1,
            "description": "",
            "defaultPrice": 0,
            "isVisible": true,
            "doses": 8,
            "isVaccine": true
          },
          "note": null
        }
      ],
      "mode": "dispensary",
      "subtotal": 0,
      "outstanding": null,
      "user1": null,
      "insuranceDiscountRate": null,
      "insuranceDiscountAmount": null,
      "isCancellation": false
    },
   [...]
  },
[...]
}
```

### Related areas to think about
This won't fix the data for any vaccinations that have already been recorded for Kiribati.

### CODE REVIEW

**Review by joshxg — CHANGES_REQUESTED** [review]
Ah choice thanks - a little off road but since we're here, can we also remove the name notes from the patient? It's recursively adding all name notes and becomes gigantic when dispensing a few times to the same patient 🙈 🙄

**Comment by katherine-sussol** [comment]
> Ah choice thanks - a little off road but since we're here, can we also remove the name notes from the patient? It's recursively adding all name notes and becomes gigantic when dispensing a few times to the same patient 🙈 🙄

Good idea 🙀  419443dd

I didn't remove it from `name.toJSON()` as it kind of looked like we might still want the name notes when doing: https://github.com/openmsupply/mobile/blob/6ed294bd41c43a3e2f2577d6daa4b936aaf2320b/src/reducers/Entities/NameReducer.js#L47 ? (I didn't dig too far though)

**Review by joshxg — APPROVED** [review]
Yeah defo the way to go, cheers! 👍

**Comment by ArpitaSussol** [comment]
@katherine-sussol i am not sure about what Payload is here. 
I created vaccination and checked in record broswer under name_note table 

{"bonusDose":false,"vaccineDate":"20/09/2021","refused":false,"itemName":"EFAVIRENZ 200 MG CP SECABLE ","expiry":"2023-03-31T18:15:00.000Z","itemCode":"AR33161","vaccinator":"vacinator1 vlast","batch":"7242145","extra":{"vaccinator":{"firstName":"vacinator1","lastName":"vlast","code":"","isActive":true},"patient":{"dateOfBirth":311019300000,"phoneNumber":"","id":"382A777DE0FB744C9D3474F5287D0246","isSupplier":false,"country":"","supplyingStoreId":"76CB9C35E4E2C241AD7DDB52D71639AF","name":"ancien, nono stable","emailAddress":"","barcode":"*9816/01/17/00083*","code":"9816/01/17/00083","isVisible":true,"nameNotes":[],"addressOne":"","firstName":"nono stable","addressTwo":"","isManufacturer":false,"lastName":"ancien","type":"patient","middleName":"","masterLists":[],"isActive":true,"isCustomer":true,"isPatient":true,"female":true,"thisStoresPatient":false,"isEditable":false}},"refusalReason":""}

is this correct behavior?

**Comment by katherine-sussol** [comment]
@ArpitaSussol Hmm - there should be something with "prescription" in there somewhere (and nameNotes shouldn't be there under the patient). 

I just checked and I think this change got missed from the release/8.3.0 branch which I used to create the 8.3.0-rc1 build (oops sorry 😢 - I think it will need to be retested in the next build)

**Comment by ArpitaSussol** [comment]
> @ArpitaSussol Hmm - there should be something with "prescription" in there somewhere (and nameNotes shouldn't be there under the patient).
> 
> I just checked and I think this PR got missed from the release/8.3.0 branch which I used to create the 8.3.0-rc1 build (oops sorry 😢 - I think it will need to be retested in the next build)

ohh okay i will hold this issue's test for next release apk. Thanks !!

**Pull request merged**
