### PR TITLE
#4068 Add barcode field to mobile schema

### LINKED ISSUE #4068: Add barcode field to realm schema
## Is your feature request related to a problem? Please describe.

Child of #4066

## Describe the solution you'd like

The ability for mobile to store a patient's barcode

## Implementation

- Add barcode field to realm `Name` object
- Update sync utils to include barcode 

## Describe alternatives you've considered

None really.

## Additional context
N/A

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #4068

## Change summary

- Add `[name]barcode` to realm schema. 
- Already exists in desktop with placeholder values (in the format `*[name]code*`)

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Sync and check realm explorer to see if it's there?

### Related areas to think about

Not sure

### CODE REVIEW

**Review by mark-prins — CHANGES_REQUESTED** [review]
The `schemaVersion` will need incrementing :)

**Comment by mark-prins** [comment]
Does the field need to be populated when a patient is looked up?
Currently the field has `placeholderBarcode` in it.

**Comment by katherine-sussol** [comment]
> The `schemaVersion` will need incrementing :)

🙀  thanks, I forgot about that!

**Comment by katherine-sussol** [comment]
> Does the field need to be populated when a patient is looked up?
> Currently the field has `placeholderBarcode` in it.

Hm, probably 😿 , 757feee0 hopefully got everything needed for lookups, now I'm wondering if I've missed any other use cases 😅

**Comment by mark-prins** [comment]
>Does the field need to be populated when a patient is looked up?

I think probably yes, but 🤦  the `/patient` api doesn't return it.
That will need to be updated if the barcode is to be looked up - I suspect that there is desktop work required anyway ( will need changes to be able to search by barcode )

**Review by mark-prins — APPROVED** [review]
Great!

**Comment by katherine-sussol** [comment]
> > Does the field need to be populated when a patient is looked up?
> 
> I think probably yes, but 🤦 the `/patient` api doesn't return it.
> That will need to be updated if the barcode is to be looked up - I suspect that there is desktop work required anyway ( will need changes to be able to search by barcode )

Yeah, there is an issue for it here https://github.com/sussol/msupply/issues/8840, I just realised I'd modified my local mSupply to expose barcodes for testing which is why I was seeing them even though they aren't technically there. Jumped the 🔫   a bit but will re-test when it is done for reals

**Pull request merged**
