### PR TITLE
seed survey

### LINKED ISSUE #3763: vaccine dispensing : survey not seeded when dispensing
## Describe the bug

When dispensing a vaccine, the patient survey form is not seeded with the most recent data.
The patient editing ( through `Dispensing` ) does pre-populate the form.

### To reproduce

Steps to reproduce the behaviour:

1. Edit a patient using the standard `Dispensing` and add something to the survey form
4. Dispense using `Vaccinations` and observe the survey form

### Expected behaviour

The survey form should be pre-populated with the most recent survey.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #3763 

## Change summary

Lifted the code from the patient edit and tested 😉 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Select an existing patient, who has survey data filled in previously. Should pre-populate, but create a new 'NameNote' record

### CODE REVIEW

**Review by joshxg — APPROVED** [review]
👍

**Review by joshxg — CHANGES_REQUESTED** [review]
🤔 

It worked and then I went back to the feature branch and it was working there also..

This same action is dispatched when selecting a patient in tab1: `selectPatient` callback- so it's calling it twice, now. I'm not sure if this PR is actually doing anything, although I could be mistaken 😁

**Comment by mark-prins** [comment]
oh. hehe. thanks - it wasn't working for me, but I may have been on an old branch. 
will recheck.

**Comment by mark-prins** [comment]
Oh, yeah. works now on feature branch 🤷‍♂️

**Pull request closed without merging**
