### PR TITLE
#3613 JSONForm in PatientEditModal

### LINKED ISSUE #3616: Add a createRecord case to create a vaccine prescription
## Is your feature request related to a problem? Please describe.

- We need to create a 'special' vaccine prescription.
- The vaccine prescription will be created in-memory and have all details filled in memory. This is in contrast to regular operations, where we create a `realm` object and then update that `realm` object.
- So, we need a `createRecord` case, which will take an in-memory vaccine prescription and save a new CI 

## Describe the solution you'd like

- A new case in `createRecord` which accepts a vaccine-prescription object and saves it persistently

## Implementation

see `createRecord.js`

## Describe alternatives you've considered

- We need to make the prescription in memory, which will have most of the details in the object already. So, this case might actually just end up being `database.update("Transaction", prescription)` without actually adding any value.
- The only real reason for suggesting this is to be consistent with the rest of the app.

## Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3616 

## Change summary

- Adds a `PatientEditModal` component to encapsulate some of the code a little
- Adds `JSONForm` into `PatientEditModal` in a somewhat crude way
- Adds creating new name notes from the `PatientEditModal`

## Testing

- [ ]  When editing a patient, can fill the survey with some details and have a name note created
- [ ] When editing a patient, can only save the form when all values, including those of the survey are valid
- [ ] No changes to behaviour when no survey

### Related areas to think about

image

Few issues to come out of this
- Tidy up UI of this modal
- Create some sort of `touched` state which gets set after an `update` action, and only save/create a new name note if the form has been touched (Could check if the actual diff is different also, but a simple `touched` is gonna catch the majority of cases and is a bit simpler. Although could just do a `JSON.stringify` compare of the new name note data and the old name note data to see if anything has changed to check also.
- I don't really like the implementation in general, but I think we are gonna do more work in this area with AEFI's so kinda just wanna have it working and spend time on the area when we're doing AEFI's, otherwise we might do something we have to change when we do AEFI's anyway. Also AEFI's.

### CODE REVIEW

**Comment by mark-prins** [comment]
There's a separate issue with the validation when the schema is undefined ( #3689 )

Working around that - with no schema the layout is still expecting a survey form: can we stretch across the page like it used to?

Screen Shot 2021-03-08 at 10 34 52 AM

**Review by mark-prins — COMMENTED** [review]
Changes look good! 
The note didn't save for me - am testing now :(
Also the layout when there is no schema, could you have a look at that please?

**Comment by mark-prins** [comment]
ok, yeah. tester configuration error. saving nicely.

**Review by mark-prins — APPROVED** [review]
Code is good 👍 
would be nice to tweak the layout if the schema is undefined

**Comment by joshxg** [comment]
Updated styles, but also realise I never tested making a new patient! Working on a fix for that now....!

**Comment by joshxg** [comment]
OK a bit hacky but should be handling new names now: 
cb709ac

**Pull request merged**
