### PR TITLE
#3819 Remove doses from batch records

### LINKED ISSUE #3819: Remove doses field
## The suggestion

We have changed the way we calculate open vial wastage to only use inventory adjustments which have an `openVialWastage` reason.

This was the primary reason for having a `doses` field. 

**Why?**

Now, we only allow `doses` to equal `quantity*number of doses per vial`, so we don't need to store the number of doses.

## Describe alternatives you've considered

Leave it

## Additional context

- By removing this field, it is much better to calculate things. For example, if you change an item to be a vaccine and to have doses, then we need to figure out what to do with historic stuff. For example, do item batches now have a number of doses? So should we go and update all the item batches? Transaction batches? etc

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3819 

## Change summary

- Removes doses field

## Testing

- [ ] Issuing stock by doses in customer invoices correct decreases the item batch quantity
- [ ] stock changes in stocktakes correctly decreases/increases the item batch quantity
- [ ] Issuing stock in vaccine dispensing correctly decreases the item batch quantity

### Related areas to think about

N/a

### CODE REVIEW

**Comment by mark-prins** [comment]
If I try to create a CI, I'm told `This invoice has items with an invalid amount of doses!`
Comes back to the transaction `hasValidDoses > TransactionItem.hasValidDoses > TransactionBatch.hasValidDoses (removed)`

**Comment by mark-prins** [comment]
I'm getting some strangeness with the stocktake quantity entry, which may not be related. Pressing backspace makes the number jump around.

https://user-images.githubusercontent.com/9192912/111936800-4f95bd00-8b2b-11eb-8701-6399dfad95aa.mov

**Comment by joshxg** [comment]
Removed the remaining doses stuff and added a toFixed around the `StocktakeItem` - seemed to be just funny double precision stuff

**Review by mark-prins — APPROVED** [review]
Cool - all working nicely thanks

**Pull request merged**
