### PR TITLE
#3287 ReactNative bump

### LINKED ISSUE #3287: Bump react-native again to 0.63.4
## Is your feature request related to a problem? Please describe.

Want this commit https://github.com/facebook/react-native/commit/00d9deaf6ba26c605694d303bb0cb072fceae5a1

## Describe the solution you'd like

Bump react native dependency

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3287 

## Change summary

- Bump RN 

## Testing

- [ ] App runs

### Related areas to think about

N/A

### CODE REVIEW

**Review by katherine-sussol — DISMISSED** [review]
👀  (and works) good to me

**Comment by joshxg** [comment]
❤️ Is it my masses of github extensions which dismiss reviews after I do a commit or is that just how github does stuff now?

🤷 Forcing a merge with admin rights is gonna kick me in the butt soon I bet

**Comment by katherine-sussol** [comment]
> ❤️ Is it my masses of github extensions which dismiss reviews after I do a commit or is that just how github does stuff now?

So offended 🙀 ! Actually it looks like it's a Github option doing this https://github.com/isaacs/github/issues/1157 (I don't have access to view the settings so can't verify, but it happened to my PR as well: https://github.com/openmsupply/mobile/pull/3275)

**Comment by joshxg** [comment]
Oh cooool I disabled it on this repo, don't tell anyone (also poke me if it's not removed and I messed up!)

**Pull request merged**
