### PR TITLE
Release/v5.0.3

### PR DESCRIPTION
**Pull request by wlthomson**
Release candidate for v5.0.3.

Fixes sync bug on looking up patient with one or more insurance policies.

### CODE REVIEW

**Comment by joshxg** [comment]
Assuming this is waiting for  #2920 and #2921

**Comment by wlthomson** [comment]
@joshxg I thought of those more as non-breaking feature changes rather than bug fixes, so have targeted them at `5.1.0`. All good?

**Comment by joshxg** [comment]
@wlthomson don't mind - just their base says different!

**Comment by wlthomson** [comment]
> mm - package.json changes? If it's being done different - sorry!

huh

**Comment by wlthomson** [comment]
> Obligatory: Don't forget

bugdance

**Pull request merged**
