### PR TITLE
#5100 Chinese translation

### LINKED ISSUE #5100: Require Chinese translation
## Is your feature request related to a problem? Please describe.

No, It is a fully new functionality

## Describe the solution you'd like

- Take translation
- Import it
- Make a changes to cope with new translation
- Handle showing Flag

chinese

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

**Moneyworks job code : ZENITH04**

### PR DESCRIPTION
**Pull request by bijaySussol**
Fixes #5100 

## Change summary

mobile with Chinese text

## Testing

- [ ] Take the latest APK
- [ ] Pull the data from central server
- [ ] From User login screen
- [ ] Tab on to select the Language
   - [ ] No error is expected
- [ ] Selected the language `Chinese `
   - [ ] No error is expected
- [ ] Login
   - [ ] The mobile app is on Chinese language
- [ ] Test creating
   - [ ] Customer invoice
      - [ ] Should work fine
   - [ ] Supplier invoice
      - [ ] Should work fine
   - [ ] Stock take
      - [ ] Should work fine
   - [ ] View stock
      - [ ] Should work fine
   - [ ] Everything that msupply offering
      - [ ] Should work fine 
  - [ ] Sorting the column
      - [ ] Should work fine
  - [ ] Sorting the column

### CODE REVIEW

**Review by sworup — APPROVED** [review]
Most of this is adding Chinese translations and Chinese as a language selection. This does not have new code so it most definitely should work. The only concern would be if there are alignment issues after text replacement, which is also unlikely.

Approved!

**Comment by bijaySussol** [comment]
@nisha-dangol : 
The test APK is here: https://www.dropbox.com/s/2vq91ok0igj92n5/mSupplyMobile-8_6_3-rc1-Chinese-universal-release.apk?dl=1

Could you please take a lead on testing this Chinese Language changes for a Client please?
Remember, If you are doing it or anyone you assign to, Please help to record time in MW.
No Job Code for now, But it will be there soon

Thank you

**Comment by AnushaUp** [comment]
## Testing
TESTED IN `8.6.3-rc1`
- [ ] Take the latest APK
- [ ] Pull the data from central server
- [ ] From User login screen
- [ ] Tab on to select the Language
   - [ ] No error is expected
- [ ] Selected the language `Chinese `
   - [ ] No error is expected
- [ ] Login
   - [ ] The mobile app is on Chinese language
- [ ] Test creating
   - [ ] Customer invoice
      - [ ] Should work fine
   - [ ] Supplier invoice
      - [ ] Should work fine
   - [ ] Stock take
      - [ ] Should work fine
   - [ ] View stock
      - [ ] Should work fine
   - [ ] Everything that msupply offering
      - [ ] Should work fine 
  - [ ] Sorting the column
      - [ ] Should work fine
  - [ ] Sorting the column

**Comment by AnushaUp** [comment]
@bijaySussol Its woking fine👍

**Comment by bijaySussol** [comment]
> @bijaySussol Its woking fine👍

Thank you @AnushaUp .

**Pull request merged**
