### PR TITLE
#3438 new sensor pages styles

### LINKED ISSUE #3438: New sensor step 2 & 3 layout improvements
## Is your feature request related to a problem? Please describe.

Current:

image

image

## Describe the solution you'd like

Needs same aesthetic as the other pages, such as VaccineModulePage. 

## Implementation

I think basically rows need margins. The `Paper` components likely need flex set to 0.

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #3438 ?

## Change summary

Just needed to tweak the styles to make things happy.

<details>
<summary>screenshots</summary>
Screen Shot 2021-02-02 at 9 05 51 AM
Screen Shot 2021-02-02 at 9 17 22 AM

</details>

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Add new sensor
- [ ] Go through each step, it looks nice. [Vaguely like the designs hopefully](https://marvelapp.com/prototype/55aea8f/screen/75648026)

### Related areas to think about

Would tidy things up in these pages, as well as other pages, to just put some margin in the `EditorRow` component. Then wouldn't have to have the stylesheet repeated everywhere and the `style` prop using it on every component based on `EditorRow`. If reviewer likes this I can do so, would just take a mo. Might result in wrangling needed elsewhere, though.

### CODE REVIEW

**Comment by Chris-Petty** [comment]
Once you see it you can't un-see it: header component on `Paper` negates rounding on top corners. Header probably needs rounding applied to top corners to match the container.

image

**Review by mark-prins — CHANGES_REQUESTED** [review]
Changes look good!
One extra request though - the gap between the label `Sensor Name` and the textbox is huge, and makes it look like the name textbox belongs to the label `Sensor Code` 

Would you mind tightening up the gap on that?

**Comment by joshxg** [comment]
I have a pathetic nit:

Because of the margin to 'account for elevation' the paper component can't align nicely with other things and I can't un see it (it's more noticeable on the `VaccinePage` aligned with the `New Sensor` button. Think margins 

image

**Comment by Chris-Petty** [comment]
> I have a pathetic nit:
> 
> Because of the margin to 'account for elevation' the paper component can't align nicely with other things and I can't un see it (it's more noticeable on the `VaccinePage` aligned with the `New Sensor` button.
> 

Totally fair! I cannot unsee it either. Do you reckon I apply equal margin to the bottom container (the `back` button and caution icon on left are also misaligned), or remove the margin on on `Paper` and put padding on page container instead? Other ideas?

**Comment by Chris-Petty** [comment]
> Changes look good!
> One extra request though - the gap between the label `Sensor Name` and the textbox is huge, and makes it look like the name textbox belongs to the label `Sensor Code`
> 
> Would you mind tightening up the gap on that?

@mark-prins Wondering which way around that would work better, making the input wider, flex stretch, or other?

**Comment by joshxg** [comment]
I think you can maybe leave it lol. But generally I like the idea that margins are layout based and should be applied to children from a parent - although I forget this a lot

**Comment by Chris-Petty** [comment]
Side note: designs had the elements in a different order (Logging above sensor details). Anyone bothered? @joshxg may have originally laid out? 

image

**Comment by joshxg** [comment]
@Chris-Petty easier than thinking about keyboard

**Comment by Chris-Petty** [comment]
> I think you can maybe leave it lol. But generally I like the idea that margins are layout based and should be applied to children from a parent - although I forget this a lot

I think that might be better, but I've been kind of doing the inverse 🤐 . E.g. dictating the layout of rows based on the vertical margins of elements within the row. I was going to say that I was trying to follow the approach demonstrated in the [FlatList docs](https://reactnative.dev/docs/flatlist#example) but then I just reviewed it... it uses a container (parent) `View` for each item in the flatlist to get the sizing. Oops 🤦 !

Wish this convo would be nested in github, ugh. UI designers huh!

**Comment by Chris-Petty** [comment]
> @Chris-Petty easier than thinking about keyboard

Almost gave me a panic attack, I've had it off for a while 😱

**Comment by Chris-Petty** [comment]
@mark-prins I made the base `TextEditor` a bit wider, that good? I'm wary about going much further because of my emulator screen is fairly wide I think
image

**Comment by mark-prins** [comment]
> @mark-prins I made the base `TextEditor` a bit wider, that good? I'm wary about going much further because of my emulator screen is fairly wide I think

The textbox is still rubbing up against the label for the code. Ideally it should be left aligned, so that it is closer to its own label, but that's fine. just leave it.

**Review by mark-prins — APPROVED** [review]

**Comment by Chris-Petty** [comment]
> > @mark-prins I made the base `TextEditor` a bit wider, that good? I'm wary about going much further because of my emulator screen is fairly wide I think
> 
> The textbox is still rubbing up against the label for the code. Ideally it should be left aligned, so that it is closer to its own label, but that's fine. just leave it.

Ah yea. Originally I did do that but felt it looked a bit funny. Or at least not consistent with the designs (again, maybe the designs work a bit better with a smaller screen than what I'm emulating).

**Comment by joshxg** [comment]
I made a new issue here #3449

**Pull request merged**
