### PR TITLE
#2057 Auto-generate patient codes

### LINKED ISSUE #2057: Prepend unique patient code prefix to patient codes
## Is your feature request related to a problem? Please describe.

Need unique patient prefixes for each patient

## Describe the solution you'd like

use `${storeCode}${NumberSequence.somePatientSequence}` to pre-prepend to every patient

## Implementation

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2057 

## Change summary

- Just auto-generates patient codes
- Makes the uneditable
- Thought I was going to prepend to codes, but after playing with the desktop preference, codes weren't editable? Maybe this is wrong? 🤷‍♂ 

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

**Comment by mark-prins** [comment]
patient codes are editable in desktop? in my db you can, but you have to click the little padlock to enable editing... unless the preference is enabled - the one to auto-generate patient codes. 
I was wondering if the auto-generating functionality should be respecting that preference? it's a global pref on the dispensary mode tab.

**Comment by joshxg** [comment]
@mark-prins 

From my playing around - need to have the auto-generate for prefixes - which makes the code non-editable (no padlock)

image

Unless I'm doing something wrong?

Regarding the global pref: mobile doesn't currently receive them - maybe something to make an issue for .. later

**Comment by mark-prins** [comment]
@joshxg hm?
Screen Shot 2020-02-03 at 9 57 55 AM

set to VISIBLE if`<>ab_prefs{13}` is FALSE

**Comment by joshxg** [comment]
So confused :(

image

image

**Comment by mark-prins** [comment]
but yeah - given that we don't sync general prefs, it would be safer to just go for it

**Comment by mark-prins** [comment]
> So confused :(

I was too! 🤣 ( did the same thing ). The second patient you create has 'zam1' though.

**Pull request merged**
