### PR TITLE
#4652 allow saving prescription with confirm status

### LINKED ISSUE #4652: Allow saving prescriptions in a state before finalising
## Is your feature request related to a problem? Please describe.
Ivory Coast want to be able to save a prescription without it being finalised (ie. they want to be able to close the prescription, come back to it, and still be able to edit it). 

## Describe the solution you'd like

**Proposed Solution**
- Add some kind of button ('Save for later'? 'Save and Close'? 'Confirm and Close'?) to step 2 and step 3 of Dispensing in Mobile:
  -  image
- When this button is clicked, exit out of dispensing without deleting the prescription in 'cn' state
- On the dispensing menu, move the search bar (and table) down so there is room for an extra toggle ('prescriptions') - this is in line with the CI/SI search bar positioning:
  - image
- On the new screen display all 'cn' prescriptions (just another table similar to 'current' CIs)? This will allow deletion but not finalisation
  - Clicking any 'cn' prescription will take the user back to step 2 of the dispensing flow (exact page up for discussion, but there isn't too much to be done on step 3 and step 1 is just picking a prescriber, which is arguably not yet a valid prescription).
  - The dispensing parameters will be pre-populated with the previously entered details
- Believe 'Customer Invoices' already excludes confirmed prescriptions from the 'current' tab - but to be double checked (don't want customers to be able to edit here).
- There is no requirement for any changes to how finalised prescriptions are handled/displayed - so retain current behaviour, i.e:
  - Patient history will continue show a patient's finalised dispensing history (believe un-finalised ones will not show up here - to be double checked)
    - image
  - Finalised prescriptions will continue to show up as a 'Past' customer invoice (weird - but this is current behaviour, and it is not editable 🤷)
    - image
    - image

**Other considerations/Info**
- Selecting a patient on the dispensing page already creates a transaction in mobile in a confirmed state - current mobile behaviour is to delete it when 'cancel' is pressed on any of the tabs. It's currently possible for these to get lost in the aether (at least from a UI perspective) if someone is mid-dispensing and force closes the app.
- Tested dispensing with payments enabled, and the app will crash if a payment amount is less than the total sell price and attempting to confirm a prescription. To be addressed as a separate issue. 
- The buttons are in an odd place when payments are not enabled. Would really like to move them down for consistency:
  -  With payments image
  - Without payments image

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

- Splitting out actual dispensing from patients into two separate menu options
  - Pros: Can follow the existing 'Current/Past' toggle behaviour used for CIs/SIs/Requisitions 
  - Cons: The menu is already getting pretty cluttered, and adding a sub menu adds an extra step to the process...
- CIs in 'cn' state are editable already - update the UI to let users edit prescriptions there (add in extra fields for prescriptions?)
  - Pros: Don't need to add extra screens to mobile
  - Cons: Confusing. Prescriptions are conceptually different from CIs so going into the CI menu to edit it is not intuitive 

## Additional context

Job Code: 

CILIP-P3M | Côte d'Ivoire (not billable) Phase 3 - Mobile Customizations
-- | --

Requirement: [NEXF025](https://docs.google.com/document/d/1wbz3MFvEpNkOz6taXJp4_kPqnTjbD0Q2/edit#heading=h.8wbvj8dsr05r)

56 hours budgetted

[NFM_CUST] CI NFM3 - Customisations

### PR DESCRIPTION
**Pull request by arjunSussol**
Fixes #4652 

## Change summary

Save confirmed prescription, make it visible to CI current tab.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Go to `Dispensing`
- [ ] Create a prescription
- [ ] There is a new button `Save & Close` in step 2 and 3 of prescription. Once you click this button, the prescription will be saved as confirmed transaction/prescription and go back to dispensing main page.
- [ ] A confirmed prescription should be visible to current tab on customer invoice. Once you click that confirmed prescription, it will take to Dispensing page and all previous saved values should be visible as it is.
- [ ] For a finalized prescription and ci, it will be as previously. Just navigate to ci page only.
- [ ] If payment module is enabled and have a total value > 0 calculated for dispensed item then `Save & Close` will be disabled and a modal generated that `You have entered a payment, this prescription must be finalised. If you want to save the prescription you must clear the payment details`. Either you have to finalise by clicking Finalise button(renamed from `Confirm`) it delete it by clicking `Cancel` button
- [ ] Otherwise create a confirmed or finalized prescription
- [ ] Only finalized prescription should be visible to patient history.
- [ ] Check confirmed prescription with insurance policy and payment type, both should be worked perfectly.
- [ ] For existing confirmed prescription, the payment type, discount rate and insurance policy should be set as set previously.
- [ ] Insurance policy should sync between mobile and desktop.
- [ ] One more thing you will notice that, the prescription will remain confirmed if you just go back with back arrow button
- [ ] Better to check by enabling/disabling the payment module and insurance policy module

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

### CODE REVIEW

**Comment by anildahalsussol** [comment]
@arjunSussol: As shown few things:
1. Transline is not synced but stock is reduced. Can cause a ledger issue so should we make the same as the customer invoice?
2. Finalised and save and close both buttons were disabled while playing with payment.
3. Strange when we get the existing cn prescription then it was changed to fn. Not sure if was it expected or if your changes made it though the code doesn't seem like that.

**Comment by arjunSussol** [comment]
> @arjunSussol: As shown few things:
> 
>     1. Transline is not synced but stock is reduced. Can cause a ledger issue so should we make the same as the customer invoice?
> 
>     2. Finalised and save and close both buttons were disabled while playing with payment.
> 
>     3. Strange when we get the existing cn prescription then it was changed to fn. Not sure if was it expected or if your changes made it though the code doesn't seem like that.

@anildahalsussol issue 1st and 3rd are existing which was there for finalized prescription only.
Now, as we are going to manage confirmed prescription I removed above conditional code and allow to sync confirmed prescription.

Issue 2nd is not a bug, it checks the existing condition related to insurance and payment. So, no need to change anything here.

However, during testing this issue I noticed that there were some existing bugs and that could affect the confirmed prescription. Major bugs I noticed are:
1) InsurancePolicy incoming sync failed, however outgoing sync works well.
2) On existing confirmed prescription, the already set insurance policy and payment type cannot be visible on DDL.
3) On existing confirmed prescription, the insurance policy discount rate is not visible as already set.
4) On Transaction > insurancePolicy is queried by wrong database field `nameInsuranceJoin.id`, however the existing and accurate field is `nameInsuranceJoinID`

I have to fix all of the above bugs to manage confirmed prescription without any issues.

Previously, the confirmed prescription were not created and only finalized prescription were managed in mobile site.
That could be reason the above bugs and issues were ignored, but now we have to fix all those. 

@ujwalSussol @JonnaQuismundo @DhanyaHerath @mark-prins 
As mobile is very much buggy, I have to spend about 4 working days to fix the issues and bugs that mentioned above.

**Comment by ujwalSussol** [comment]
> @ujwalSussol @JonnaQuismundo @DhanyaHerath @mark-prins
> As mobile is very much buggy, I have to spend about 4 working days to fix the issues and bugs that mentioned above.

@arjunSussol  : thanks, today I will plan to review this.

**Comment by arjunSussol** [comment]
Updated test case after further improvements.

**Review by ujwalSussol — APPROVED** [review]
@arjunSussol  :  working great 👍  

@anildahalsussol  Thanks for testing.

**Pull request merged**
