### PR TITLE
Release/8.4.0

### LINKED ISSUE #4437: v8.4.0 Release Discussion
## RELEASE VERSION

v8.4.0 

### SUMMARY

There are no major features currently planned.
This release is primarily aimed at misc bug fixing and minor enhancements 

The deadline is TBD based on demand.

Also includes issues from https://github.com/openmsupply/mobile/issues/4438

### Chores
TBD

### Refactors/Enhancements
TBD

### Features
- #4498 

### Bugs
- #4511 
- #4485
- #4516 

## Documentation
- TBD

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #4437

## Change summary

- It's been over 20 days since the last RC and no _major_ issues have been raised/identified with mobile, so should we release?
- Kiribati are looking to upgrade to newest mobile so would be good to make sure they have got all the latest fixes/changes
- MAC Address format for cold chain in mobile has been changed. Doesn't break core functionality/integration, but might break any existing reporting if someone who was using mobile cold chain was to update.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Run app, confirm working.
- [ ] Check bugs in issue, confirm fixed as described.

### Related areas to think about

N/A

### CODE REVIEW

**Review by joshxg — DISMISSED** [review]
OK ! 

I would maybe expect that it would be easier to publish the msupply-ble-service onto npm and add it as a dep there rather than using yalc, which I believe was mainly just for the main development as it was easier and meant we wouldn't end up with a npm package with a version of 0.0.123123

Also obligatory reminder for bugsnag source maps and schema version check (if there were any new fields/tables added!)

**Comment by katherine-sussol** [comment]
> I would maybe expect that it would be easier to publish the msupply-ble-service onto npm and add it as a dep there rather than using yalc, which I believe was mainly just for the main development as it was easier and meant we wouldn't end up with a npm package with a version of 0.0.123123


Thanks that's a good point - I'll see if I can get onto the sussol account...

**Comment by katherine-sussol** [comment]
Whoops - I think Github auto-dismissed the last review because there were commits pushed after approval. Sorry @joshxg going to be annoying and re-request 😸  thanks for reviewing!

**Review by joshxg — APPROVED** [review]
All good!

🎉

**Pull request merged**
