### PR TITLE
Release 8.4.2

### PR DESCRIPTION
**Pull request by katherine-sussol**
For #4552

## Change summary

- Bumps version for release
- 8.4.2 RC2 with http allowed appears to be working well in training so time to release? 👍 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Test the issues claimed to be fixed in the parent issue

### Related areas to think about
Have also merged #4579 to allow http from Android 9 and above

### CODE REVIEW

**Review by joshxg — DISMISSED** [review]
I mean, sure! 

This has just the change for the bluetooth/back button and the button text size?

What are we doing about the http 'problem'? 🤔  Who makes the end decision on that 🤷

**Comment by mark-prins** [comment]
> What are we doing about the http 'problem'? 🤔 Who makes the end decision on that 🤷

I'm now thinking that we go ahead and do it - though I don't like the idea, I haven't seen a suitable alternative to get around the problem that people are having.

**Comment by katherine-sussol** [comment]
> This has just the change for the bluetooth/back button and the button text size?

Yup - nothing very exciting 🙄  - just need a proper release for the non-training environment. 

> What are we doing about the http 'problem'? 🤔 Who makes the end decision on that 🤷

Uhm. Good question... I dunno. If we include it and someone exposes a server via http, we just say it's a server problem? 🏃‍♀️

**Comment by joshxg** [comment]
sounds good to me

**Comment by katherine-sussol** [comment]
Cool - I'll test PR #4579 merge it into Release/8.4.2 then if it is working as expected 👍  (sorry might need a a re-approval once done - think GitHub will auto dismiss)

**Review by joshxg — APPROVED** [review]

**Pull request merged**
