### PR TITLE
#4234 refusal comment

### LINKED ISSUE #4234: Vaccine dispensing: Refusal comment area
## Is your feature request related to a problem? Please describe.

When refusing a vaccine, offer the user the ability to add a comment/reason for the refusal.

## Describe the solution you'd like

- When the `refuse` checkbox is checked, turn the item select area to a text input.
- Allow the user to enter a reason/comment

## Implementation
- Save the comment/reason against the refusal name note

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #4234 

## Change summary

Adds a refusal reason text element when 'refused' is checked. The reason entered is saved to the `note` of the refusal name note, so is viewable in mSupply. Sync to and from the server - even though from the server is somewhat pointless.

The name note is only created if refused, so I'm not clearing the text if you check-uncheck-check..  

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] refuse and enter some text: sync and see what is on the server

### CODE REVIEW

**Review by joshxg — COMMENTED** [review]
Works well- just looking a little bit odd when I try to type

image

**Comment by mark-prins** [comment]
How would you feel about changing `android:windowSoftInputMode` to `adjustPan`?
It works nicely for me and makes the other screens nice to use as well, but it is a global change to help me out with a single issue..

refusal

**Review by joshxg — APPROVED** [review]
I've always been a little too scared to change it, you're so much ballsy!!

It works well.. I tested a bit.. dispensing is ok

image

changekeyboard

I think there is a whole bunch of logic on the data table component to do scrolling and stuff which might be messing with it.. specifically this line (so much bunches!) https://github.com/openmsupply/mobile/blob/f353f013a798a289d6779a8fbe31246d25a258db/src/widgets/DataTable/DataTable.js#L88 

I say we merge it in and deal with the fallout if there's any and it's not just me!

Unless, of course, they actually want a drop down! 🤣

**Comment by mark-prins** [comment]
thanks. I'm still nervous.. at least this is an RC version 🤷‍♂️ 

seems to work ok in the screens I've looked through. good spotting with the datatable - that one is working ok for me so far. I guess we'll find out where the problems are

**Pull request merged**
