### PR TITLE
adjust layout on keyboard open

### LINKED ISSUE #4276: Soft keyboard overlaps text input fields on login page
## Describe the bug

screen

Logging as a bug just because it's been a bit annoying being unable to see if you're typing the correct thing into the input fields when using the soft keyboard. It seems like the footer content is being pushed above the keyboard, but the rest of the content is stubborn and doesn't move.

The workaround is to just use a Bluetooth keyboard all the time 🤣 

### To reproduce

Steps to reproduce the behaviour:

1. Ensure there is no Bluetooth keyboard connected to the tablet, and try to login to mSupply mobile
2. Observe issue in screenshot

### Expected behaviour

Expect the content to move above the keyboard when the soft keyboard is opened.

### Proposed Solution

Not sure yet

### Version and device info

- App version: 8.2.0-rc2
- Tablet model: Lenovo / Emulator (anything not huge?)
- OS version: Android 8.1

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #4276 

## Change summary

This has finally bothered me enough to actually fix it.
Adjusting the margin of the login modal, depending on the state of the soft keyboard. 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Login modal adjusts for soft keyboard
- [ ] First use page adjusts for soft keyboard
- [ ] Request a demo store modal adjusts for soft keyboard

### CODE REVIEW

**Review by joshxg — APPROVED** [review]
if it works for you, call!

Doesn't for me on my emulator (tablet is charging oops!) but my emulator does seem to have an excessively large keyboard 🤔 

image

**Comment by mark-prins** [comment]
this is my emulated version: 
Screen Shot 2021-07-29 at 9 44 49 AM

works ok for me on the emulator and tablet - @kat do you want to have a look before I merge?
I'll change the destination branch, as we'll get a release out before you're back.

**Comment by katherine-sussol** [comment]
> works ok for me on the emulator and tablet - @kat do you want to have a look before I merge?
> I'll change the destination branch, as we'll get a release out before you're back.

Works great on my regular tablet (Lenovo TB-X304L w/Android 8.1) and emulator (Nexus 10 w/Android 10.0).

Tested on a Nexus 9 w/Android 8.1 and could replicate Josh's screenshot:
image

I'm guessing it's just the largeness of the keyboard, maybe there is a way to get the keyboard height and adjust the margin that way? 🤔  But it does still look better with this adjustment than without!

**Comment by mark-prins** [comment]
Ok, let's just merge and raise another issue if we want to proceed with further changes :)

**Pull request merged**
