### PR TITLE
#3655 handle dob better

### LINKED ISSUE #3655: Handle date of birth better
## Is your feature request related to a problem? Please describe.

When searching for patients in the vaccine dispensary process, once a Date of Birth has been entered, it isn't possible to clear the field and broaden the search.

## Describe the solution you'd like

Some way of searching for all patients after entering a DOB
Suggestions:

- Allow entry of blanks in that field
- A button to clear the DOB field
- A reset button for the form, like this was 1995

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3655	

## Change summary

- Handles empty dates better
- Fixed a bug which had empty inputs be todays date when creating a patient

## Testing

- [ ] Can delete the date of birth in the patient select form and have it still be valid

### Related areas to think about

N/A

### CODE REVIEW

**Review by wlthomson — APPROVED** [review]
LGTM.

**Comment by mark-prins** [comment]
@joshxg Change looks good thanks!

I managed to break it though - enter anything, clear the date field and try to use the date picker - gives this:

```
Invariant Violation: A date or time should be specified as `value`.

This error is located at:
    in RNDateTimePicker (at FormDateInput.js:151)
    in RCTView (at View.js:34)
    in View (at FlexColumn.js:33)
    ...
```

**Comment by joshxg** [comment]
Ugh yeah, sorry. That `FormDateInput` is a nightmare. Who wrote that..!

This will fix the crash (mainly the `?? new Date()` as the seed was `null`): 913a554

Also fixing seeding the input with an epoch (for the next tab to have a valid date initially when seeding with the DOB from the `name` object): 
7dc70f5

**Comment by mark-prins** [comment]
@joshxg error gone!
There's a thing with validation still - which could be fixed with #3663 
- Enter a date, search button enabled.
- Clear date, search button disabled.. can't search any more!

**Comment by joshxg** [comment]
Will make sure it's all good in #3680!

**Pull request merged**
