### PR TITLE
#3308-4 New fonts

### LINKED ISSUE #3308: New editing rows
*EPIC: #3161*

*Related Marvel Designs: https://marvelapp.com/prototype/55aea8f*
*Related Component Breakdown: https://app.diagrams.net/#G1wLg12JAQyrgB6D3F_X0O9LBZwJs8PcJM

## Is your feature request related to a problem? Please describe.

In the new vaccine module designs there are different style of editing rows:

Examples:

image
image
image

This issue is to discuss the implementation of these editable areas to try and create a solution which easily enables different styles of rows to edit different fields.

## Describe the solution you'd like

Unsure 100% just yet.

Still thinking about the API for this. I think I would like to see some sort of `Row` style component which can be composed of different `RowEdit` components?

Something like:

```
<Row>
    <RowLabel icon="X" text="Y"/>
    <RowTemperatureEdit currentValue={} someCallbacks/>
    <RowDurationEdit currentValue={} someCallbacks/>
</Row>
```

## Implementation

Create components:

- [ ] `TextInputWithMask`
- [ ] `TextInputWithAffix`
- [ ] `BaseStepperButton`
- [ ] `BaseStepperInput`
- [ ] `StepperInputWithLabel`
- [ ] `DurationEditor`
- [ ] `TemperatureEditor`
- [ ] `TimeEditor`
- [ ] `DateEditor`
- [ ] `TextEditor`
- [ ] `EditorRow`

## Describe alternatives you've considered

TBD

## Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3308

## Change summary

- Adds new fonts in the marvel designs for vaccines
- Have checked them out and seem to work?

## Testing

Internal

### Related areas to think about

N/A

### CODE REVIEW

**Comment by Chris-Petty** [comment]
Late to the party but isn't it not ideal to be propagating a new font? Font inconsistency in an application is sin afaik 😅 .

**Comment by joshxg** [comment]
@Chris-Petty I dunno.. and it's not too late. 

I'm happy to revert, I wasn't going to but it's just so much easier to just follow the design ..

**Comment by Chris-Petty** [comment]
> @Chris-Petty I dunno.. and it's not too late.
> 
> I'm happy to revert, I wasn't going to but it's just so much easier to just follow the design ..

I'm at least 80% Manu didn't intend for there to be different fonts under a different workflow, I imagine he just went for it cause he didn't know mobile's font is `museo slab` and `Roboto` is the android default. I wonder if Manu has a github account, we could just tag him here?

Speaking of defaults, it's the default in react native android so we I don't think we need to add in the font files; smol APK yey 🙂 .

To change it for the whole app it is:
image

Which is equivalent to:

image

**Comment by Chris-Petty** [comment]
Side note, be cooler if RN Android had [downloadable fonts](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts) to save on APK size.

**Comment by joshxg** [comment]
there's use of museo in the marvel designs as well as roboto

**Comment by Chris-Petty** [comment]
I pinged Manu an email asking to clarify.

I skimmed through the designs looking for museo; I think just the sync text and the "Download" button text for the log data? Strictly following the design, "Cancel" button text size also changes 😉 :
Screen Shot 2021-01-14 at 4 37 01 PM
Screen Shot 2021-01-14 at 4 37 08 PM

**Comment by Chris-Petty** [comment]
@joshxg At any rate, pretty sure Roboto is supported out of the box in RN Android (just specify `fontFamily: Roboto` in stylesheets, if not just omitting it so long as a given component doesn't inherit it from a parent), so can close this PR?

**Comment by joshxg** [comment]
@Chris-Petty do you mind since I'm branched a bit to let me revert this afterwards?

**Comment by Chris-Petty** [comment]
Ya sure. I'll approve this and make an issue to remove the files and what not.

**Review by Chris-Petty — APPROVED** [review]

**Pull request merged**
