### PR TITLE
#2554 fix modal strings not centred

### LINKED ISSUE #2554: Modal string is not centred( create new patient details and create a new prescriber)
## Describe the bug

Modal string is not centred when you create a new patient and asking for patient details and the same as to create a new prescriber.
Some related issues been closed but issues still remain.
https://github.com/openmsupply/mobile/issues/2532#issuecomment-597830571

Screen Shot 2020-03-17 at 1 50 45 PM
Screen Shot 2020-03-17 at 1 51 18 PM
Screen Shot 2020-03-19 at 10 14 34 AM

### To reproduce

1. Go to 'dispensary'
2. Click on 'new patient' and "new prescriber"
3. See error

### Expected behaviour

modal string to be centered

### Proposed Solution

Make textAlign to be centered.

### Version and device info

- App version: v4.0.1
- Tablet model: emulator
- OS version: 

### Additional context
similar to https://github.com/openmsupply/mobile/issues/2476

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2554.

Branched from #2561.

## Change summary

Just a small style change to centre modal titles.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Modal titles are centred (e.g. create new patient, create new prescriber).

### Related areas to think about

N/A.

### CODE REVIEW

**Comment by mark-prins** [comment]
I'm confused? I've done this already: https://github.com/openmsupply/mobile/pull/2535

**Comment by wlthomson** [comment]
@mark-prins Yeah, the issue came up in testing on `master`. I saw your fix and just copied it here so we can close out the issue. Probably could have just left it for develop, but it was a bit distracting working with it on `master`!

I think good to keep bug fixes to patches and leave `develop` only for new functionality (fixes will get merged back into `develop` anyway). Since testing is on `master`, if a bug is fixed on `develop`, the tester won't see it and will probably raise it (I think what happened here?) Either way, this is targeted as a patch fix, which I plan to release today, so still worth getting in IMO.

**Comment by wlthomson** [comment]
> in that case.. great work! looks good to me ;)

:laughing: . 

Was thinking maybe the above is a bit too strict. It's probably a losing game trying to change processes and enforce all non-functionality changes as patches, so rephrasing as "keep bug fixes to patches **where possible**" :smiley:.

**Comment by mark-prins** [comment]
> > in that case.. great work! looks good to me ;)
> 
> 😆 .
> 
> Was thinking maybe the above is a bit too strict. It's probably a losing game trying to change processes and enforce all non-functionality changes as patches, so rephrasing as "keep bug fixes to patches **where possible**" 😃.

I agree with your `master` / `develop` and `feature` / `patch` distinctions. 
And this PR is a good reminder, thanks.

**Comment by Rebecca367** [comment]
@wlthomson @mark-prins 
I think that I have issued one issue similar to these as well.
https://github.com/openmsupply/mobile/issues/2476

It's pretty hard to keep track of feature, develop and master branch and when to merge what to what...at least it's confusing to newbie, especially we don't know each step of work each other  is doing?! So one issue been solved but after a while the same issue occur again. It causes frustration over time.

**Comment by wlthomson** [comment]
> @wlthomson @mark-prins
> I think that I have issued one issue similar to these as well.
> #2476
> #2532
> 
> It's pretty hard to keep track of feature, develop and master branch and when to merge what to what...at least it's confusing to newbie, especially we don't know each step of work each other is doing...maybe can find a solution for people's life easier?

I can understand for people new to git its a bit tricky, but our system is quite simple (simpler than most open-source software projects I've contributed to!). The processes are used because they make life easier, not harder! Removing our branching structure would make it much harder to work as a team on separate pieces of work (especially now that we are remote!) and also harder for our support team to document things and ensure customers are running compatible versions of desktop and mobile.

We're using "semantic versioning", which means we have three "types" of release: major, minor, and patch (e.g. `4.0.2` has a major version of `4`, a minor of `0`, and a patch of `2`).

The `master` branch is the current release. We target all releases at `master`. 

As we want to reduce the amount of merging into the main branches (`develop` and `master`), we prepare a release by merging related work into a `release` branch. In the case of a patch, that branch consists of a number of PRs. For minor/major, we usually just branch directly off `develop` (which will contain recently merged `features` etc., see below). 

When we are ready to release, we merge the release into `master` and `master` is merged back into `develop` (`develop` should always have everything `master` has in it).

That's the main workflow. Since you're not 100% comfortable with it, I would suggest not merging anything unless you're sure! When doing testing, if you are testing on `master` you are essentially testing a version that we feel can be released to customers (and may be already being used). If you are testing on `develop`, you are testing our "internal" version which has not yet been released.

Feature branches are not "core" to the workflow, they are just a tidy way of reducing the amount of "traffic" going into `develop`. Instead of constantly merging into `develop`, we make a `feature` branch and merge all related work into that. When the feature is ready, we merge the `feature` into `develop`. 

Hope that helps!

**Comment by Rebecca367** [comment]
@wlthomson 
Thanks for explaining all these to me. It definitely helps. Would you recommend testers to test on master branch to get the most accurate results that users might be get after using mobile?

**Comment by wlthomson** [comment]
@Rebecca367 It depends on the situation. Most of the time, you'll want to be testing on `develop`. Once something is in `master`, it's ready for customers and should already be tested. So everything in `master` should already be tested. But because bugs slip through, we will sometimes need patches (as explained above). So the only time you'll be testing on `master` is if you're testing a patch (remember that patches don't go to `develop` first, they go straight to `master`). 

Makes sense?

 The main thing is to make sure you wait until the work has been merged before you test it. If it's a PR for a patch, you'll want to check it's made its way to `master` before testing it.

**Comment by Rebecca367** [comment]
@wlthomson 
cool, thank you for the explanation again. It's clear enough for me now.

**Pull request merged**
