### PR TITLE
Add recommit of changes

### LINKED ISSUE #1608: Scripts for exporting json to csv and back to js for localization files
Related with issue #484 

By now, all localization strings are hard-coded in js files, which makes it difficult and time consuming when sending for translation.

The final purpose of this feature is to create a script that export JSON localization files to CSV, ready to send for translation. Once translated, strings are imported as JSON again and placed in the corresponding localization file.

## Implementation

- Replace all `js` files under /localization for `JSON` files
- Modify /localization/index.js to import those new `JSON` files and export its corresponding LocalizedStrings
- Create`convertJsonToCsv.js` to do the exporting json to csv and add a script in package.json to run this feature in the command line. Something like: `yarn json-to-csv [selectedLangague]`
- Create`convertCsvToJson.js` to do the exporting csv to json and add a script in package.json to run this feature in the command line. Something like: `yarn csv-to-json [selectedLangague]`
- Create a doc explaining main details of this feature, installation and usage.

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1608 

This is a recommit of the PR from #1661

### CODE REVIEW

**Comment by joshxg** [comment]
I am a little worried I've missed something with this, but it will be relatively minor and cause less problems than if I don't merge this and add a whole bunch of localization for the 3 feature branches currently running.

**Comment by Rebecca367** [comment]
@joshxg @diegoevangelisti @mark-prins 
Is there anything broken or causing conflicts in #1608? 
#484 is resolved but are there any tests need to be done?

**Comment by joshxg** [comment]
@Rebecca367 There was a mistake with the commit of #484 which meant I had to revert all of the commits and then recommit them in this PR. Since you know the testing of #484 quite well, do you mind giving it another quick test to make sure it is still ok? Cheers!

**Comment by Rebecca367** [comment]
@joshxg @diegoevangelisti 
I have done testing on log-in page that #484 is about on version 3.1.1.
Is it OK to elaborate on what kind of mistake of commit is it of #484, so that we can learn from this experience after diego comes back? i know of there were conflicts of #1608 when diego was working on it but I didn't catch on the mistakes.

## Testing on version 3.1.1

Steps to reproduce or otherwise test the changes of this PR:

Log in page:
- [x] Check `Password` and `User name` placeholders
- [x] Enter a valid user name and password and check the `Logging in...` message
- [x] Enter an invalid username or password and check text `Invalid username or password`

**Comment by joshxg** [comment]
@Rebecca367 

We can go over the mistake when diego is back on Wednesday as it is definitely a good learning opportunity. 

I'm confused by your testing? Where did those test cases come from? The PR with the test cases for this was https://github.com/openmsupply/mobile/pull/1661 here?

**Comment by Rebecca367** [comment]
@joshxg 
Test cases are from closed PR #484 
Screen Shot 2020-01-06 at 11 58 00 AM

**Comment by Rebecca367** [comment]
@joshxg 
I only tested #484 because there are 2 parts in localization. #1608 looks fine after testing but I am not sure of #484.
So, run through #1661 as well?

**Comment by joshxg** [comment]
@Rebecca367 

Oh ok.. if you don't mind please do a quick export/import, just to double check it is ok :) thanks!!

**Pull request merged**
