### PR TITLE
Release 8.5.0

### LINKED ISSUE #4541: v8.5.0 Release Discussion
## RELEASE VERSION

v8.5.0 

### SUMMARY

There are no major features currently planned.
This release is primarily aimed at bug fixing of high priority/value issues (but not high enough of a priority to have been included in a patch).

NB: When upgrading to this version of mobile, if using the vaccine dispensing feature (i.e. If there is a PatientEvent with code = 'vaccination') - mSupply Desktop needs to have a VaccinationEvent formSchema added. Example here (internal repo): https://github.com/sussol/client-JSON-schemas/blob/main/Kiribati/COVID-19-vaccination-rollout/VaccinationEvent.JSON

The deadline is TBD based on demand.

#### Features
- #4613

#### Bug fixes
- #4625
- #4486
- #4618
- #4562
- #4592

#### Features
- #4623 
- #4635
- https://github.com/openmsupply/mobile/issues/4684

#### Bug fixes
- #4640
- #4563
- #4644 - superseded by #4680
- #4665
- #4680

#### Bug fixes
- #4724

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #4541

## Change summary
- Officially release 8.5.0 (no new changes introduced since 8.5.0-rc2) - fixes (of which most are pre-existing issues also reproducible in 8.4.2) to be done via patches as none are breaking for Kiribati which is being deployed tomorrow.
- If there is a vaccination event in mSupply Desktop, before upgrading to 8.5.0, it is important to ensure there is a 'VaccinationEvent' form schema also present in mSupply Desktop, otherwise the app will crash when trying to view history.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Check the items in the linked issue discussion that have been completed - ensure they work. 

### Related areas to think about
Will need to do another PR back to develop after this commit as `master` and `develop` are protected branches

### CODE REVIEW

**Comment by katherine-sussol** [comment]
image

👀  That is one determined bot

**Comment by katherine-sussol** [comment]
Sorry, @mark-prins (and thanks for all of your reviews!) - these aren't any new changes from 8.5.0-rc2 other than a `package.json` version bump, I can't merge directly to master (and it is safer to have another pair of 👀   in case I've done something silly) so have requested a review from you 😅

**Comment by mark-prins** [comment]
## Testing

#### Features
- [ ] #4613

#### Bug fixes
- [ ] #4625
- [ ] #4486
- [ ] #4618
- [ ] #4562
- [ ] #4592

### RC1 (Release [here](https://github.com/openmsupply/mobile/releases/tag/v8.5.0-rc1))

#### Features
- [ ] #4623 
- [ ] #4635
- https://github.com/openmsupply/mobile/issues/4684

#### Bug fixes
- [ ] #4640
- [ ] #4563
- [ ] #4644 - superseded by #4680
- [ ] #4665
- [ ] #4680

### RC2 Candidates

#### Bug fixes
- [ ] #4724

**Comment by mark-prins** [comment]
Testing notes:
- Portuguese translation is missing some translations (or perhaps Cold Chain has no translation? there's a stray `Sync Enabled` which switches to `Sinc Ativo` on another screen 🤷 )
- `Faire Clignoter` doesn't fit still!

**Review by mark-prins — APPROVED** [review]
👍  All looks good to me!
thanks Kat 😁

**Comment by katherine-sussol** [comment]
> Testing notes:
> 
> * Portuguese translation is missing some translations (or perhaps Cold Chain has no translation? there's a stray `Sync Enabled` which switches to `Sinc Ativo` on another screen 🤷 )
> * `Faire Clignoter` doesn't fit still!

Thanks for the testing 😍! I have also noticed a few niggles, I think for some strings even when there is a localised string available there are still some components that are not being updated when the language is switched 🤔  - the dispensary header (also found by @nisha-dangol here https://github.com/openmsupply/mobile/issues/4725) is another instance. I'll log some issues for those two!

**Pull request merged**
