### PR TITLE
#4367 Add dateRange option to JSONForm DatePicker

### LINKED ISSUE #4367: Option to prevent future date selection in date pickers
## Is your feature request related to a problem? Please describe.

A user would like to prevent their users from selecting a future date when recording the date of vaccination for a patient. 

image

## Describe the solution you'd like

Can we add this as a configurable option to the JSON DateWidget?

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #4367

## Change summary

- Adds the ability in mobile to disable past/future dates via uiSchema config

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] This uiSchema config should only allow past dates (and today's date):
 `"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "past" } },`
- [ ] This uiSchema config should only allow future dates (and today's date):
`"date": { "ui:widget": "DateWidget", "ui:options": { "dateRange": "future" } },`
- [ ] This uiSchema config should allow any dates:
`"date": { "ui:widget": "DateWidget" },`

### Related areas to think about
- The patient hub requires a separate update/PR
- Lots of ways to do this change, alternative suggestion: https://github.com/openmsupply/mobile/issues/4367#issuecomment-901670153 - went with UISchema update as I thought of it as more of a UI/widget specific concern rather than an underlying data thing (although could work either way)

### CODE REVIEW

**Review by mark-prins — APPROVED** [review]
LGTM! that works nicely. we should update the docs with this new option :)

**Comment by katherine-sussol** [comment]
> LGTM! that works nicely. we should update the docs with this new option :)

Good idea! Do we have any sort of existing 'Guide to configuring your JSON Schemas' anywhere yet? Otherwise, could add  a child page here maybe? https://sussol.net/wiki/doku.php/projects:vaccinations:setup

**Comment by katherine-sussol** [comment]
> Good idea! Do we have any sort of existing 'Guide to configuring your JSON Schemas' anywhere yet? Otherwise, could add a child page here maybe? https://sussol.net/wiki/doku.php/projects:vaccinations:setup

I put it here: 
https://sussol.net/wiki/doku.php/projects:vaccinations:jsonschemaconfig#datepicker_for_string_type_elements

Very rough WIP 😸

**Comment by mark-prins** [comment]
> Very rough WIP 😸

That is already awesome! thanks, that'll be super helpful

**Pull request merged**
