### PR TITLE
#4180 breach lines not showing

### LINKED ISSUE #4180: Breach lines not showing on bar chart
## Describe the bug

It's #4053 all over again.
the hot and cold breach lines aren't showing on the bar chart.

### To reproduce

Steps to reproduce the behaviour:

1. Go to vaccine bar chart

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #4180 

## Change summary

The rendering problem which was visible with the line chart is also affecting the bar chart.
Also fixed the default, which was incorrectly set to `line` while working on that one

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Check the bar chart

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

### CODE REVIEW

**Review by joshxg — COMMENTED** [review]
Cool- just confused by the diff?

**Comment by joshxg** [comment]
Changed the base to 8.1.1 but still getting the weird diff 🤔

**Comment by mark-prins** [comment]
> Cool- just confused by the diff?

me too 🤷‍♂️

**Comment by mark-prins** [comment]
Ok, killing off this mutant PR.. #4185

**Pull request closed without merging**
