### PR TITLE
#3504 Limit logging delay to 30 minutes

### LINKED ISSUE #3504: Limit logging delay and logging interval
## Is your feature request related to a problem? Please describe.

In the spec for the 30 day fridge monitor (not the data logger from the original requirements):

```
The period of delay (Logging delay, not the above pause period) should not exceed 30 minutes when subjected to the following operating conditions: 
	•	Device temperature at time of introduction to refrigerated environment: +43°C. 
	•	Temperature of refrigerated environment: +5°C. 
	•	Air movement in refrigerator: Still air, no circulation fan.
```

The spec also has:

```
Logging interval:
The device must measure the storage temperature at intervals not exceeding 10
minutes and log all relevant data at intervals not exceeding one hour.
```

I believe the original spec was 24 hours

## Describe the solution you'd like

- Limit logging delay to 30 minutes.
- Limit logging interval to 10 minutes? 60 minutes?

## Implementation

Change the logging delay to use the duration picker rather than date/time picker

## Describe alternatives you've considered

Putting in a air movement sensor

## Additional context

Maybe this doesn't fully meet the spec, but 🤷

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3504 

## Change summary

- Update log interval to be a max of 10 minutes
- Update log delay to be a duration picker and a max of 30 minutes

## Testing

Internal

### Related areas to think about

N/A

### CODE REVIEW

**Comment by mark-prins** [comment]
I had some hunchy funchy on the first run through: 

Screen Shot 2021-02-16 at 5 48 43 PM

The 'start logging' shows `NaN` minutes and the interval can go beyond 10 minutes.
Reloading the app fixed the limit - the `NaN` might just be me? I have a suggestion..

**Comment by mark-prins** [comment]
@joshxg my suggestion wasn't needed.. I think what is required is adding `logDelay` to `createSensor` in `SensorManager`
I'm getting an undefined `logDelay` otherwise in step three. I'm also getting 4 minutes, when it should be 5??

**Comment by joshxg** [comment]
Argh, Sorry about that.

- I'd forgotten to commit this: 16aa4e0
- To fix the `4` not `5`: 2301f7a - Basically to do with setting up the `logDelay` and then a few seconds going by and then the next step using the `current` time rather than `logDelay-5 days`
- `minutes` -> `minute` from the other PR 21d94f5

**Comment by mark-prins** [comment]
> I'd forgotten to commit this: 16aa4e0
perfect, thanks

> To fix the 4 not 5: 2301f7a
Yeah, that's what I thought. I managed to get a 3 minute in one test as well - I blame the tester for that one!

> minutes -> minute from the other PR 21d94f5
Yeah, still embarrassed at how nit-picky that was.

**Review by mark-prins — APPROVED** [review]
great!

**Pull request merged**
