### PR TITLE
#3614 Additional name fields

### LINKED ISSUE #3614: Add additional fields to the name data type
## Is your feature request related to a problem? Please describe.

We need to add additional fields to the `[name]` data type which are not currently there.

## Describe the solution you'd like

Add the following tables to the schema, including to incoming sync
- `[Ethnicity]`
- `[Nationality]`
- `[Occupation]`

Add the following fields to `[name]`
- ethnicity: Relation to the `Ethnicity` table
- occupation: Relation to the `Occupation` table
- religion (nationality???): Relation to the `Religion` table (????????????)
- District - UNSURE HOW TO HANDLE THIS
	- New field? Address?
- Village - UNSURE HOW TO HANDLE THIS
	- New field? Address?

## Implementation

Add the fields to `[name]`, add the fields to `incomingSyncUtils` and `outgoingSyncUtils`

## Describe alternatives you've considered

N/A

## Additional context

Resource spreadsheet: https://docs.google.com/spreadsheets/d/1eYqarZ9KDnK8F6k0Yx0HwuRYt-1SajSd/edit#gid=91174836

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3614 

## Change summary

- Added `[Nationality]`, `[Ethnicity]` and `[Occupation]` fields.
- Was working on it and realised I remember something about not using name categories for the address' were said. Also realise that even if we were to use the name categories, we'd need the list of districts/villages somewhere, and also need to have some sort of `if (tonga)` condition to display those fields? I'm thinking that just putting district/village in the JSON schema form is an easier solution...?

### This is not testable until https://github.com/sussol/msupply/pull/8135 is merged
- [ ] `[nationality]` table syncs to mobile
- [ ] `[ethnicity]` table syncs to mobile
- [ ] `[occupation]` table syncs to mobile

### Related areas to think about

N/A

### CODE REVIEW

**Comment by mark-prins** [comment]
yes - I too was thinking of adding village etc to the schema.
Someone did say not to use `name_categories`, so I thought to try just passing in the big big lists to the schema.

We also talked about dependency of data; select a village and the district & region would magically be picked for you.. 
And also a better UI component for selecting from a huge list..

**Comment by mark-prins** [comment]
For testing...
```
C_COLLECTION($cNewOnes; $cCurrentOnes)
C_OBJECT($oItem)
C_TEXT($tItem)

$cNewOnes:=New collection("Health care workers"; "Teacher"; "Police"; "HMAS"; "Fire brigade"; "Airport Workers"; "Sea Port Workers"; "Unemployed"; "Other")
$cCurrentOnes:=ds.Occupation.all().toCollection().extract("name")

For each ($tItem; $cNewOnes)
	If ($cCurrentOnes.indexOf($tItem)=-1)
		$oItem:=ds.Occupation.new()
		$oItem.ID:=UUID_generate
		$oItem.name:=$tItem
		$oItem.save()
	End if 
End for each 


$cNewOnes:=New collection("Tongan"; "Fijian"; "Samoan"; "American"; "Indian"; "Chinese"; "Other")
$cCurrentOnes:=ds.nationality.all().toCollection().extract("description")

For each ($tItem; $cNewOnes)
	If ($cCurrentOnes.indexOf($tItem)=-1)
		$oItem:=ds.nationality.new()
		$oItem.ID:=UUID_generate
		$oItem.description:=$tItem
		$oItem.save()
	End if 
End for each 

$cNewOnes:=New collection("Tongan"; "Fijian"; "Chinese"; "Indian"; "Italian"; "Caucasion"; "Other Pacific Islands"; "Other")
$cCurrentOnes:=ds.Ethnicity.all().toCollection().extract("name")

For each ($tItem; $cNewOnes)
	If ($cCurrentOnes.indexOf($tItem)=-1)
		$oItem:=ds.Ethnicity.new()
		$oItem.ID:=UUID_generate
		$oItem.name:=$tItem
		$oItem.save()
	End if 
End for each 
```

**Review by mark-prins — APPROVED** [review]
LGTM!

**Comment by joshxg** [comment]
Yeah I think passing in the big big lists will do.. I also thought that if we just have them select the one field we can do the dependent things later on when reporting.. 🤷

**Pull request merged**
