### PR TITLE
#4613 Translate remaining strings to Pt

### LINKED ISSUE #526: Phrase is not being translated: "Invalid username or password"
Build Number: 2.0.0

Description: If the user set a wrong username or password, while using other language, the app is not translating the phrase "Invalid username or password". There is no translation for that phrase.
image

Reproducible: Yes

Reproduction Steps: On login screen change the language to other than English (button 'Language' on the bottom left of the login screen). Than type an username with wrong password.

### LINKED ISSUE #4613: Portuguese translation
## Is your feature request related to a problem? Please describe.
Sao Tome are going to start using mSupply mobile within about 2 months. We need the Portuguese version for them.

## Describe the solution you'd like

Make it speak Portuguese.

## Implementation

Hand it to Nicole who will work her tappity, tappity, tap magic.

## Describe alternatives you've considered

Doing it myself. Cough. Not really.

## Additional context
None

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes #4613 

## Change summary

Add remaining string in Pt for São Tomé

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Check if strings in Pt fit the screen - consider **new functionality** since all main feature were already translated previously

### Related areas to think about

Also fixes #526 with [mSupply/Desktop](https://github.com/sussol/msupply/pull/10468) PR. Although the solution is based on the language selected in mSupply Desktop! so it's not perfect, it just make the language selection most consistent if used both in mSupply desktop AND mobile.

### CODE REVIEW

**Review by joshxg — APPROVED** [review]
awesome!

**Comment by nmadruga** [comment]
I wasn't been able to test until now, so have noticed a couple of things today:

Problem 1) Cutting of on **Customer Requisitions** button:
Screen Shot 2022-03-14 at 9 57 07 PM

Problem 2) Even though I haven't translated the term "Cold Chain" itself, it seems that most things aren't getting translated in this part of the App. Any clues?
Screen Shot 2022-03-14 at 10 00 42 PM
Screen Shot 2022-03-14 at 9 58 32 PM
Screen Shot 2022-03-14 at 9 58 18 PM
Screen Shot 2022-03-14 at 9 57 53 PM
Screen Shot 2022-03-14 at 9 57 37 PM 



@joshxg Do you knoe how I could change the UI? Maybe using something to wrap and fit the button to the size in case it's a big string like that? I think we also need some solution for Spanish strings. Could you help with a tip about the UI please?

**Comment by joshxg** [comment]
Ah - 

Problem 1) Smaller string? 😁  Increase height to allow for two lines? 
Problem 2) Looks like vaccine strings needs to be added here: https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/localization/utilities.js#L44

**Comment by nmadruga** [comment]
> Problem 1) Smaller string? 😁 Increase height to allow for two lines?

Do you mean condition to the size of the string right? I'm not sure where to change the UI... If you could give a hand with that it would be very nice. Thanks

> Problem 2) Looks like vaccine strings needs to be added here

Will do that.

**Comment by joshxg** [comment]
This component is the button on that screen. https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/pages/MenuPage.js#L108-L111

I meant use less characters 😁

**Comment by nmadruga** [comment]
> I meant use less characters 😁

😝 I wish, but Pt is this beautiful and prolific language.

> This component is the button on that screen.

Thank you. I think I could try changing this based on how many letter are present in the string. What do you think?
https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/pages/MenuPage.js#L274

**Comment by joshxg** [comment]
Good idea.

My first thought is because the second row of text within the button is sooo close to showing.. maybe some micro adjustments to the height/padding for *all* will be fine. 

I.e. if it is just a small increase and height and change in padding/margin which is not really noticeable for the other ones.. may as well do the easy solution.

The styling I think is here: https://github.com/openmsupply/mobile/blob/737e0c9ca1baaf38dbfa74207ca356ba04c629a0/src/globalStyles/buttonStyles.js#L65-L77 - there is quite a lot of padding. For example maybe padding: 10 and height: 65/70 might look OK and allow for the second line of text to show

**Comment by katherine-sussol** [comment]
R.e The cold chain strings - some of them are still hardcoded in the app (in addition to needing to add vaccine strings to localisation). We found out when updating the French translations for a demo 😅 , but we didn't update at the time because Cold Chain wasn't a part of the demo.

I noted a few examples but there are possibly more:
https://github.com/openmsupply/mobile/issues/4486

**Comment by nmadruga** [comment]
After a long run... Finally some good results on the Style!

See what do you think now slight change on fontSize in -1 when text is longer and fixed it being cut off:
Screen Shot 2022-03-15 at 1 04 13 PM
Screen Shot 2022-03-15 at 1 02 32 PM

**Comment by nmadruga** [comment]
> R.e The cold chain strings - some of them are still hardcoded in the app (in addition to needing to add vaccine strings to localisation). We found out when updating the French translations for a demo 😅 , but we didn't update at the time because Cold Chain wasn't a part of the demo.
> 
> I noted a few examples but there are possibly more: #4486

Thanks for poping in Kat. I can have a look on that after lunch - if that's helpful. I think it should be good have everything on localized strings indeed. It helps with future work to be localising only. So, will do that on a different PR.

**Review by GaryWilletts — APPROVED** [review]
Parece maravilhoso! But I don't really feel qualified 😉

**Pull request merged**
